### ISSUE TITLE
Captain's Favor (& 400 Tickets?) non-interaction with Sale Star

### ISSUE THREAD

**Issue by ConqAra** [prodzpod/Hex3Mod#1]
If you have both Captain's Favor and Sale Star it'll use the Sale Star but not provide two void potentials. Can it be made so it works with Sale Star or that one of the items would take priority and the other wouldn't get used on the first chest you open when you have both items? I'm not sure if this interaction is the same for 400 Tickets, but probably worth mentioning if it is.

**Comment by prodzpod** [comment]
ok
