### ISSUE TITLE
Stuck loading at 99% after 2.1.6 update.

### ISSUE THREAD

**Issue by Aaron00000** [prodzpod/Hex3Mod#2]
Game gets stuck at 99% if RealerHex3Mod v2.1.6 is loaded, loads properly if it is disabled. [LogOutput.log](https://github.com/user-attachments/files/17447059/LogOutput.log)

**Comment by smalllbuddy** [comment]
bump

**Comment by prodzpod** [comment]
which items do you have disabled

**Comment by prodzpod** [comment]
i bet you guys disabled the base item without disabling the void variant and it exploded because it cant find the item to corrupt

**Comment by Aaron00000** [comment]
Incidentally I had Captain's Favor enabled but not 400 tickets since Sales Star exists. Might be worht adding an option to corrupt Sales Star into Captain's Favor.
